// This file is part of NUTS Finance.

// Copyright (C) 2017-2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for nutsfinance_stable_asset
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-08-10, STEPS: `[50, ]`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// target/release/node
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=*
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --template=./templates/runtime-weight-template.hbs
// --output=./runtime/src/weights/


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;
use crate::WeightInfo;

#[allow(clippy::unnecessary_cast)]
impl WeightInfo for () {
	fn create_pool() -> Weight {
		(33_115_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn modify_a() -> Weight {
		(21_186_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	fn mint(u: u32) -> Weight {
		(85_694_000 as Weight) // Standard Error: 187_000
			.saturating_add((46_172_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(u as Weight)))
	}
	fn swap(u: u32) -> Weight {
		(124_402_000 as Weight) // Standard Error: 72_000
			.saturating_add((8_138_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(9 as Weight))
	}
	fn redeem_proportion(u: u32) -> Weight {
		(107_494_000 as Weight) // Standard Error: 164_000
			.saturating_add((43_376_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(u as Weight)))
	}
	fn redeem_single(u: u32) -> Weight {
		(114_847_000 as Weight) // Standard Error: 882_000
			.saturating_add((14_613_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(7 as Weight))
	}
	fn redeem_multi(u: u32) -> Weight {
		(86_888_000 as Weight) // Standard Error: 152_000
			.saturating_add((43_556_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(u as Weight)))
	}
	fn send_mint_to_xcm(u: u32) -> Weight {
		(85_694_000 as Weight) // Standard Error: 187_000
			.saturating_add((46_172_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(u as Weight)))
	}
	fn process_xcm_mint(u: u32) -> Weight {
		(85_694_000 as Weight) // Standard Error: 187_000
			.saturating_add((46_172_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(u as Weight)))
	}
	fn receive_mint_from_xcm() -> Weight {
		(21_186_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	fn send_redeem_single_to_xcm(u: u32) -> Weight {
		(85_694_000 as Weight) // Standard Error: 187_000
			.saturating_add((46_172_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(u as Weight)))
	}
	fn process_xcm_redeem_single(u: u32) -> Weight {
		(85_694_000 as Weight) // Standard Error: 187_000
			.saturating_add((46_172_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(u as Weight)))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(u as Weight)))
	}
	fn receive_redeem_single_from_xcm() -> Weight {
		(21_186_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	fn update_xcm_asset() -> Weight {
		(21_186_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}
